apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - function-go-templating.yaml
  - function-environment-configs.yaml
  - function-auto-ready.yaml
  - rbac.yaml
  - environmentconfig-app-images.yaml
  - xrd-appinstance.yaml
  - composition-applicationinstance.yaml
