apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationinstance:aggregate-to-crossplane
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
      - secrets
      - configmaps
      - serviceaccounts
      - resourcequotas
      - limitranges
    verbs:
      - "*"

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
      - networkpolicies
    verbs:
      - "*"

  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
    verbs:
      - "*"

  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
      - clusters/status
    verbs:
      - "*"

  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
      - externalsecrets/status
    verbs:
      - "*"
      
  - apiGroups:
      - cloud.google.com
    resources:
      - backendconfigs
    verbs:
      - "*"