apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: turing-cell-497816-p0
      auth:
        workloadIdentity:
          clusterLocation: europe-west3-a
          clusterName: group-c-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
