apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    iam.gke.io/gcp-service-account: group-c-external-dns@turing-cell-497816-p0.iam.gserviceaccount.com
