apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: group-c-external-secrets@turing-cell-497816-p0.iam.gserviceaccount.com
