apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: 2510781016@hochschule-burgenland.at
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key

    solvers:
      - dns01:
          cloudDNS:
            project: turing-cell-497816-p0
